### ISSUE TITLE
Add Support for Multiple Text or ASCII art

### ISSUE THREAD

**Issue by amitkrxyz** [alefnull/dvd-term#10]
## Motivations
I'd like to have the option for multiple ASCII art texts bouncing on the screen.
- Would you like to implement this feature? N

## Solution

- Allow users to pass multiple text string
- Each ASCII art or text should move and bounce around the screen independently.

## Alternatives

N/A

## Additional context
N/A

**Comment by alefnull** [comment]
hey, thanks for the request! this actually sounds like a fun idea, and i'll definitely consider giving it a go. my initial question would be how do you envision the two (or, potentially, more) 'logos' reacting when they intersect with each other? should they just pass behind/in front of one another? or should they bounce off of each other like they do with the edges of the screen?

**Comment by amitkrxyz** [comment]
I would prefer the logos overlapping each other. Having them collide would definitely be a cool feature, though it might get a bit chaotic with multiple logos. Why not offer both options and let users choose their preference?

**Comment by alefnull** [comment]
initial testing shows promise already. going to have to spend some more time making sure everything renders correctly when they're overlapping, and make sure the performance doesn't drop too much, but so far so good :)

![image](https://github.com/user-attachments/assets/eac4e2e4-9e74-4fa9-8134-6b0641d029b6)
![image](https://github.com/user-attachments/assets/8cdebff7-8b6d-49de-bea6-2c2903950ac5)

**Comment by alefnull** [comment]
feature has been added.

app has been updated to v0.1.42, available in repo releases and on crates.io.
